version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - APP_ENV=local

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "80:80"
