apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cleanlog-ingress
  namespace: cleanlog
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: cleanlog.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cleanlog-service
            port:
              number: 80
